name: Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Create the build directory before binding so that directory is not owned by root.
      - run: mkdir -p build
      - run: ./slate.sh
      - run: echo "dev.codewars.com" > ./build/CNAME
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
